# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.srcs/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0.xci
# IP: The module: 'ZyboZ7_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboZ7_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboZ7_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboZ7_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.srcs/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0.xci
# IP: The module: 'ZyboZ7_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboZ7_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboZ7_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZyboZ7_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
