# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZyboZ7_design/ZyboZ7_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design || ORIG_REF_NAME==ZyboZ7_design} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_processing_system7_0_0/ZyboZ7_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_processing_system7_0_0 || ORIG_REF_NAME==ZyboZ7_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_axi_gpio_0_0/ZyboZ7_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_axi_gpio_0_0 || ORIG_REF_NAME==ZyboZ7_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_clk_wiz_0_0/ZyboZ7_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_clk_wiz_0_0 || ORIG_REF_NAME==ZyboZ7_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_xbar_0/ZyboZ7_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_xbar_0 || ORIG_REF_NAME==ZyboZ7_design_xbar_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_ps7_0_axi_periph_0/ZyboZ7_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZyboZ7_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_rst_ps7_0_50M_0/ZyboZ7_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZyboZ7_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_axi_dma_0_0/ZyboZ7_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_axi_dma_0_0 || ORIG_REF_NAME==ZyboZ7_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_xbar_1/ZyboZ7_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_xbar_1 || ORIG_REF_NAME==ZyboZ7_design_xbar_1} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_axi_mem_intercon_0/ZyboZ7_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_axi_mem_intercon_0 || ORIG_REF_NAME==ZyboZ7_design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_axis_data_fifo_0_0/ZyboZ7_design_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_axis_data_fifo_0_0 || ORIG_REF_NAME==ZyboZ7_design_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_xlconcat_0_0/ZyboZ7_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_xlconcat_0_0 || ORIG_REF_NAME==ZyboZ7_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_auto_pc_0/ZyboZ7_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_auto_pc_0 || ORIG_REF_NAME==ZyboZ7_design_auto_pc_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_auto_us_0/ZyboZ7_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_auto_us_0 || ORIG_REF_NAME==ZyboZ7_design_auto_us_0} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_auto_us_1/ZyboZ7_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_auto_us_1 || ORIG_REF_NAME==ZyboZ7_design_auto_us_1} -quiet] -quiet

# IP: bd/ZyboZ7_design/ip/ZyboZ7_design_auto_pc_1/ZyboZ7_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboZ7_design_auto_pc_1 || ORIG_REF_NAME==ZyboZ7_design_auto_pc_1} -quiet] -quiet

# XDC: /home/ozorakobo/Zybo-Z7/Zybo-Z7_Project/Zybo-Z7_Project.gen/sources_1/bd/ZyboZ7_design/ZyboZ7_design_ooc.xdc
